appname = syllabus_mid
httpport = ${SYLLABUS_MID_HTTP_PORT}
runmode = ${SYLLABUS_MID_RUNMODE||prod}  
parameterStore = ${PARAMETER_STORE}
autorender = false
copyrequestbody = true

AcademicaEspacioAcademicoService=${ACADEMICA_ESPACIO_ACADEMICO_SERVICE}
HomologacionDependenciaService=${HOMOLOGACION_DEPENDENCIA_SERVICE}
IdiomaService=${IDIOMA_SERVICE}
OikosService=${OIKOS_SERVICE}
SyllabusService=${SYLLABUS_SERVICE}
SyllabusSeed = ${SYLLABUS_SEED}
AcademicaCore = ${ACADEMICA_CORE_SERVICE}
